# Generated by Django 5.1.7 on 2025-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='artist_photo'),
        ),
    ]
