# Generated by Django 5.1.7 on 2025-07-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
